version: "3.8"

services:
  mm:
    image: lamnguyenx/mitmweb:13.0.0.dev0-lamguyenx
    network_mode: host
    volumes:
      - ./exp/xdgg/mm/conf_dir:/conf_dir
    command: |
      /bin/bash -vc '
        mitmweb \
          --web-host 0.0.0.0 \
          --web-port 8011 \
          --listen-port 8010 \
          --set web_password="1" \
          --set confdir=/conf_dir \
          --set block_global=false
      '
