theme = "hcl"

[editor]
text-width = 80
soft-wrap.enable = true
bufferline = "always"

[editor.statusline]
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding"]

[keys.insert]
"A-down" = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "insert_mode"]  # Move line down
"A-up" = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "insert_mode"]  # Move line up

[keys.normal]
tab = "indent"
"S-tab" = "unindent"
"A-J" = [ "extend_to_line_bounds", "yank", "paste_after" ]
"A-K" = [ "extend_to_line_bounds", "yank", "paste_before" ]
H = "goto_previous_buffer"
L = "goto_next_buffer"
"C-d" = ["search_selection", "select_mode", "extend_search_next"]
