gui:
  theme:
    selectedLineBgColor:
      - reverse
os:
  copyToClipboardCmd: 'xclip -selection clipboard || tmux load-buffer -b 0 -'
customCommands:
  - key: '<c-g>'
    command: "git diff {{.SelectedFile.Name}} | delta --light --side-by-side --line-numbers"
    context: 'files'
    description: 'Open file diff in delta (side-by-side, eink-friendly)'
    output: terminal
  - key: '<c-g>'
    command: "git diff {{.SelectedCommitRange.From}}..{{.SelectedCommitRange.To}} | delta --light --side-by-side --line-numbers"
    context: 'commits'
    description: 'Side-by-side diff between selected commits (Diff Mode)'
    output: terminal
  - key: '<c-g>'
    command: "git diff {{.SelectedLocalCommit.Sha}}~1 {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}} | delta --light --side-by-side --line-numbers"
    context: 'commitFiles'
    description: 'Open file diff in delta (side-by-side, eink-friendly)'
    output: terminal
